### ISSUE TITLE
Model is not loaded

### ISSUE THREAD

**Issue by adityamangal1998** [kaushikjadhav01/COVID-19-Detection-Flask-App-based-on-Chest-X-rays-and-CT-Scans#1]
when i load the model,i got this error
OSError: SavedModel file does not exist at: resnet_chest.h5/{saved_model.pbtxt|saved_model.pb}

please help me to resolve this error

**Comment by nitin-bommi** [comment]
The model is pointing to a location in Git Large Files. You can install that and then use the pointer to download it from the server.

**Comment by arpita739** [comment]
sorry I didn't your point. Kindly explain

**Comment by khamalfa** [comment]
I think you not using git clone command, and the quota to download the model is expire.. I suggest you train the model from jupyter notebook with google collab, download the model and, save it in models folder.

**Comment by kaushikjadhav01** [comment]
Hey hi, extremely sorry for the inconvenice. I have not been active on Github lately due to medical issues. The issues were caused due to expiry of my Github LFS. Please follow the new setup instructions and try again. Also, please make sure you have Python v 3.8.5 installed. For other versions, you might face package problems with TensorFlow
