### ISSUE TITLE
add support for tensorflow latest version and cv2

### ISSUE THREAD

**Issue by Mayur6999** [kaushikjadhav01/COVID-19-Detection-Flask-App-based-on-Chest-X-rays-and-CT-Scans#2]

**Comment by kaushikjadhav01** [comment]
Hey hi, extremely sorry for the inconvenice. I have not been active on Github lately due to medical issues. The issues were caused due to expiry of my Github LFS. Please follow the new setup instructions and try again. Also, please make sure you have Python v 3.8.5 installed. For other versions, you might face package problems with TensorFlow
